## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Stream IoT data to an autonomous database using serverless functions"
    stackDescription: "Deploy Oracle Cloud Infrastructure Streaming to support IoT devices data streams uploaded into the cloud at scale."
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid

    - title: Required Configuration
      visible: true  
      variables:
      - compartment_ocid
      - region
      - atp_admin_user
      - atp_admin_password
      - atp_user
      - atp_password
      - ocir_namespace
      - ocir_repo_name
      - ocir_docker_repository
    
    variables:

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Region where you want to deploy the resources defined by this stack."

      atp_admin_user:
        type: string
        required: true
        visibile: true
        default: "admin"
        title: "ATP admin username."
        description: "ATP admin username."

      atp_admin_password:
        type: password
        required: true
        visibile: true
        title: "ATP Admin Database password"
        description: "ATP Database password for ADMIN user"

      atp_user:
        type: string
        required: true
        visibile: true
        default: "oraapp"
        title: "ATP application username."
        description: "ATP application username."

      atp_password:
        type: password
        required: true
        visibile: true
        title: "ATP App User Database password"
        description: "ATP Database password for Application user"

      ocir_namespace:
        type: string
        required: true
        visibile: true
        title: "Oracle Cloud Infrastructure Registry (OCIR) namespace"
        description: "Oracle Cloud Infrastructure Registry (OCIR) namespace"

      ocir_repo_name:
        type: string
        required: true
        visibile: true
        title: "Oracle Cloud Infrastructure Registry (OCIR) repository name"
        description: "Oracle Cloud Infrastructure Registry (OCIR) repository name"

      ocir_docker_repository:
        type: string
        required: true
        visibile: true
        title: "Oracle Cloud Infrastructure Registry (OCIR) Docker Repository URL"
        description: "Oracle Cloud Infrastructure Registry (OCIR) Docker Repository URL" 
        

      